serenity.project.name=SWAG LABS
serenity.test.root=oren.example
webdriver.driver=firefox
webdriver.autodownload=false
webdriver.firefox.binary=C:/Program Files/Mozilla Firefox/firefox.exe
webdriver.gecko.driver=C:/Program Files/Mozilla Firefox/geckodriver.exe
serenity.browser.maximized=false
serenity.use.unique.browser=false
serenity.restart.browser.each.scenario=true
headless.mode=true
webdriver.timeouts.implicitlywait=10000
serenity.step.delay=500
